import Head from "next/head";
import { useUsers } from "../services/hooks/use-users";
import { Pagination } from "./components/Pagination";

export default function Home() {
  const { data, isLoading, isFetching, error, refetch } = useUsers();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <>
          <div style={{ display: "flex", justifyContent: "space-between" }}>
            <h1>React Query and MirageJS</h1>
            <button onClick={() => refetch()}>Refetch</button>
          </div>

          <h2>
            Users {!isLoading && isFetching && <small>Updating...</small>}
          </h2>

          {isLoading && <div>Loading...</div>}
          {error && <div>Error fetching data</div>}
          {data && (
            <ul>
              {data.map((user) => (
                <li key={user.id}>
                  {user.name} - {user.email}
                </li>
              ))}

              <Pagination
                totalCountOfRegisters={200}
                currentPage={5}
                onPageChange={() => {}}
              />
            </ul>
          )}
        </>
      </main>
    </>
  );
}
